<?xml version="1.0" encoding="utf-8"?><Database Name="StepForward" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Image" Member="Images">
    <Type Name="Image">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Image_Section_Image" Member="Section_Images" ThisKey="Id" OtherKey="ImageId" Type="Section_Image" />
    </Type>
  </Table>
  <Table Name="dbo.Section" Member="Sections">
    <Type Name="Section">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Section_Section_Image" Member="Section_Images" ThisKey="Id" OtherKey="DataId" Type="Section_Image" />
      <Association Name="Section_Type_Section" Member="Section_Type" ThisKey="Type_Id" OtherKey="Id" Type="Section_Type" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Section_Image" Member="Section_Images">
    <Type Name="Section_Image">
      <Column Name="DataId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ImageId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Section_Section_Image" Member="Section" ThisKey="DataId" OtherKey="Id" Type="Section" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Image_Section_Image" Member="Image" ThisKey="ImageId" OtherKey="Id" Type="Image" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Section_Type" Member="Section_Types">
    <Type Name="Section_Type">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Section_Type_Section" Member="Sections" ThisKey="Id" OtherKey="Type_Id" Type="Section" />
    </Type>
  </Table>
</Database>